### ISSUE TITLE
Charger sensors do no longer update automatically

### ISSUE THREAD

**Issue by gschot** [cyberjunky/home-assistant-shell_recharge#152]
### Describe the issue

Home Assistant: 2025.10.4
Shell Recharge: 0.1.13

I noticed the last couple of days that chargers seem to be occupied very long. When I checked the state of a charger in the Shell Recharge app, it shows a different state than the sensors do in HA using the Shell Recharge integration.

What do I notice:
To test, today I have connected a second charger integration (ENBW) to monitor state differences. At 14:12 I disconnected my car from a public charger near me. ENBW reports the charger available again at 14:14. The Shell recharge sensor still reports it as occupied, even after 15 minutes.
The logging for the charger shows a nice 5 minute interval of sensor updates. However, the log still shows:

`2025-11-10 14:27:06.323 DEBUG (MainThread) [custom_components.shell_recharge.sensor] uid=xxxxxxxx externalId='xxxxxxxxxx' evseId='xxxxxxxxxx' status='**Occupied**' connectors=[Connector(uid=xxxxxxx, externalId='2', connectorType='Type2', electricalProperties=ElectricalProperties(powerType='AC3Phase', voltage=230, amperage=25.0, maxElectricPower=17.3), fixedCable=False, tariff=Tariff(startFee=0.0, perMinute=0.0, perKWh=0.55, currency='EUR', updated='2025-11-10T10:42:03Z', updatedBy='Default', structure='Flat'), updated='2025-07-29T07:45:01Z', updatedBy='Feed', externalTariffId='xxxxxxxxxx')] authorizationMethods=['NewMotionApp', 'RFIDToken'] physicalReference='xxxxxxxxxxxx' updated='2025-11-09T14:09:16Z'`

The data is only refreshed correctly after I reload the specific charger entry at the Recharge integration.

<img width="290" height="62" alt="Image" src="https://github.com/user-attachments/assets/708fbd83-33e0-4cfa-b1a5-a07aab546181" />

The top bar shows the state of the ENBW sensor for this charger. At 09:56 it reports as my car being connected. The bottom bar shows the sensor in Shell Recharge integration. It does not follow the state, until I reloaded the integration at 11:09, so from that moment it shows active as well. Then I disconnected my car at 14:12, where the top bar shows the charger being available again, whereas the Shell Recharge sensor still shows the charger as being occupied. After the screenshot, I reloaded the integration again, where the Shell Recharge sensor shows the charger in the correct state (available).

Meanwhile, I reverted back to 0.1.12 to see if that does update correctly. There were no changes in charger occupancy yet, will report back how this goes.

### Reproduction steps

1. Run the Shell Recharge integration 
2. Connect a car to a free charger
3. Wait 15 minutes
4. See that Shell Recharge sensor is not updated
...

### Debug logs

```text

```

### Checklist

- [x] I have enabled debug logging for my installation.
- [x] I have filled out the issue template to the best of my ability.
- [x] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [x] This issue is not a duplicate issue of any [previous issues](https://github.com/cyberjunky/home-assistant-shell_recharge/issues?q=is%3Aissue+label%3A%22Bug%22+)..

**Comment by gschot** [comment]
After reverting back to 0.1.12 and recreate the instances, it seems to be working again for me.

**Comment by gschot** [comment]
I went back to 0.1.13 and the sensors are not updating.


![Image](https://github.com/user-attachments/assets/bad80c74-8d1d-4a70-9a1c-0144256a37cf)

Here is a screenshot of the state shown in the shell recharge app versus the sensors in HA.

I monitor some more chargers and at least 4 have changed state, where there's a mismatch with what the HA sensors show vs Shell Recharge.

Meanwhile I also updated HA to 2025.11.1

Rolling back to 0.1.12 again.

**Comment by jefdriesen** [comment]
I'm also seeing this problem with 0.1.13 and HA 2025.11.0 container.

I wonder if this has anything to do with the Shell recharge app being phased out and replaced with the Shell app? That switchover date was on November 18. This is mainly for charging an EV directly from the app, but maybe there are some API changes for the chargers too?

**Comment by jefdriesen** [comment]
I suspect the integration somehow doesn't fetch the latest status from the shell recharge api, or re-uses a cached value.

When I enable debug logging in HA, the status is wrong in the log (both chargers occupied):
```
2025-11-22 21:14:07.912 DEBUG (MainThread) [custom_components.shell_recharge.sensor] uid=5504814 externalId='BE-VIA-XXX-2' evseId='BE*VIA*XXX*2' status='Occupied' connectors=[Connector(uid=5611605, externalId='2', connectorType='Type2', electricalProperties=ElectricalProperties(powerType='AC3Phase', voltage=230, amperage=32.0, maxElectricPower=22.1), fixedCable=False, tariff=Tariff(startFee=0.0, perMinute=0.0, perKWh=0.63, currency='EUR', updated='2025-11-19T09:37:44Z', updatedBy='Default', structure='Flat'), updated='2025-10-06T13:52:13Z', updatedBy='Feed', externalTariffId='319b13f2-423f-42d4-8ff5-5619481b8d5c')] authorizationMethods=['NewMotionApp', 'RFIDToken'] physicalReference='001664-2' updated='2025-11-19T07:39:01Z'
2025-11-22 21:14:07.913 DEBUG (MainThread) [custom_components.shell_recharge.sensor] uid=5504813 externalId='BE-VIA-XXX-1' evseId='BE*VIA*XXX*1' status='Occupied' connectors=[Connector(uid=5611604, externalId='1', connectorType='Type2', electricalProperties=ElectricalProperties(powerType='AC3Phase', voltage=230, amperage=32.0, maxElectricPower=22.1), fixedCable=False, tariff=Tariff(startFee=0.0, perMinute=0.0, perKWh=0.63, currency='EUR', updated='2025-11-19T09:37:44Z', updatedBy='Default', structure='Flat'), updated='2025-10-06T13:52:13Z', updatedBy='Feed', externalTariffId='319b13f2-423f-42d4-8ff5-5619481b8d5c')] authorizationMethods=['NewMotionApp', 'RFIDToken'] physicalReference='001664-1' updated='2025-11-16T14:19:41Z'
```
But when I manually fetch the URL (`https://ui-map.shellrecharge.com/api/map/v2/locations/search/<serialnumber>`) with curl, the status is correct (both chargers available):

```
[
  {
    "uid": 4865344,
    "externalId": "XXX",
    "coordinates": {},
    "operatorName": "GreenFlux",
    "address": {},
    "accessibility": {
      "status": "Unspecified",
      "remark": "",
      "statusV2": "Public"
    },
    "accessibilityV2": {
      "status": "Public"
    },
    "evses": [
      {
        "uid": 5504813,
        "externalId": "BE-VIA-XXX-1",
        "evseId": "BE*VIA*XXX*1",
        "status": "Available",
        "connectors": [
          {
            "uid": 5611604,
            "externalId": "1",
            "connectorType": "Type2",
            "electricalProperties": {
              "powerType": "AC3Phase",
              "voltage": 230,
              "amperage": 32,
              "maxElectricPower": 22.1
            },
            "fixedCable": false,
            "tariff": {
              "perKWh": 0.63,
              "currency": "EUR",
              "updated": "2025-11-22T20:29:26Z",
              "updatedBy": "Default",
              "structure": "Flat"
            },
            "updated": "2025-10-06T13:52:13Z",
            "updatedBy": "Feed",
            "externalTariffId": "319b13f2-423f-42d4-8ff5-5619481b8d5c"
          }
        ],
        "authorizationMethods": [
          "NewMotionApp",
          "RFIDToken"
        ],
        "physicalReference": "001664-1",
        "updated": "2025-11-21T15:39:51Z"
      },
      {
        "uid": 5504814,
        "externalId": "BE-VIA-XXX-2",
        "evseId": "BE*VIA*XXX*2",
        "status": "Available",
        "connectors": [
          {
            "uid": 5611605,
            "externalId": "2",
            "connectorType": "Type2",
            "electricalProperties": {
              "powerType": "AC3Phase",
              "voltage": 230,
              "amperage": 32,
              "maxElectricPower": 22.1
            },
            "fixedCable": false,
            "tariff": {
              "perKWh": 0.63,
              "currency": "EUR",
              "updated": "2025-11-22T20:29:26Z",
              "updatedBy": "Default",
              "structure": "Flat"
            },
            "updated": "2025-10-06T13:52:13Z",
            "updatedBy": "Feed",
            "externalTariffId": "319b13f2-423f-42d4-8ff5-5619481b8d5c"
          }
        ],
        "authorizationMethods": [
          "NewMotionApp",
          "RFIDToken"
        ],
        "physicalReference": "001664-2",
        "updated": "2025-11-22T16:48:19Z"
      }
    ],
    "openTwentyFourSeven": true,
    "openingHours": [
      {
        "weekDay": "Sun",
        "startTime": "00:00",
        "endTime": "23:59"
      },
      {
        "weekDay": "Mon",
        "startTime": "00:00",
        "endTime": "23:59"
      },
      {
        "weekDay": "Tue",
        "startTime": "00:00",
        "endTime": "23:59"
      },
      {
        "weekDay": "Wed",
        "startTime": "00:00",
        "endTime": "23:59"
      },
      {
        "weekDay": "Thu",
        "startTime": "00:00",
        "endTime": "23:59"
      },
      {
        "weekDay": "Fri",
        "startTime": "00:00",
        "endTime": "23:59"
      },
      {
        "weekDay": "Sat",
        "startTime": "00:00",
        "endTime": "23:59"
      }
    ],
    "updated": "2025-10-06T13:52:13Z",
    "name": "ENGIE Vianeo publieke laadpaal",
    "locationType": "ON_STREET",
    "supportPhoneNumber": "+32 800 12 599",
    "facilities": [
      "SPORT"
    ],
    "predictedOccupancies": [
      {
        "weekDay": "Fri",
        "occupancy": 5,
        "startTime": "00:00",
        "endTime": "00:59"
      },
      {
        "weekDay": "Fri",
        "occupancy": 5,
        "startTime": "01:00",
        "endTime": "01:59"
      },
      {
        "weekDay": "Fri",
        "occupancy": 5,
        "startTime": "02:00",
        "endTime": "02:59"
      },
      {
        "weekDay": "Fri",
        "occupancy": 5,
        "startTime": "03:00",
        "endTime": "03:59"
      },
      {
        "weekDay": "Fri",
        "occupancy": 5,
        "startTime": "04:00",
        "endTime": "04:59"
      },
      {
        "weekDay": "Fri",
        "occupancy": 4,
        "startTime": "05:00",
        "endTime": "05:59"
      },
      {
        "weekDay": "Fri",
        "occupancy": 4,
        "startTime": "06:00",
        "endTime": "06:59"
      },
      {
        "weekDay": "Fri",
        "occupancy": 4,
        "startTime": "07:00",
        "endTime": "07:59"
      },
      {
        "weekDay": "Fri",
        "occupancy": 4,
        "startTime": "08:00",
        "endTime": "08:59"
      },
      {
        "weekDay": "Fri",
        "occupancy": 4,
        "startTime": "09:00",
        "endTime": "09:59"
      },
      {
        "weekDay": "Fri",
        "occupancy": 4,
        "startTime": "10:00",
        "endTime": "10:59"
      },
      {
        "weekDay": "Fri",
        "occupancy": 4,
        "startTime": "11:00",
        "endTime": "11:59"
      },
      {
        "weekDay": "Fri",
        "occupancy": 4,
        "startTime": "12:00",
        "endTime": "12:59"
      },
      {
        "weekDay": "Fri",
        "occupancy": 4,
        "startTime": "13:00",
        "endTime": "13:59"
      },
      {
        "weekDay": "Fri",
        "occupancy": 4,
        "startTime": "14:00",
        "endTime": "14:59"
      },
      {
        "weekDay": "Fri",
        "occupancy": 4,
        "startTime": "15:00",
        "endTime": "15:59"
      },
      {
        "weekDay": "Fri",
        "occupancy": 4,
        "startTime": "16:00",
        "endTime": "16:59"
      },
      {
        "weekDay": "Fri",
        "occupancy": 4,
        "startTime": "17:00",
        "endTime": "17:59"
      },
      {
        "weekDay": "Fri",
        "occupancy": 4,
        "startTime": "18:00",
        "endTime": "18:59"
      },
      {
        "weekDay": "Fri",
        "occupancy": 4,
        "startTime": "19:00",
        "endTime": "19:59"
      },
      {
        "weekDay": "Fri",
        "occupancy": 4,
        "startTime": "20:00",
        "endTime": "20:59"
      },
      {
        "weekDay": "Fri",
        "occupancy": 4,
        "startTime": "21:00",
        "endTime": "21:59"
      },
      {
        "weekDay": "Fri",
        "occupancy": 4,
        "startTime": "22:00",
        "endTime": "22:59"
      },
      {
        "weekDay": "Fri",
        "occupancy": 5,
        "startTime": "23:00",
        "endTime": "23:59"
      },
      {
        "weekDay": "Mon",
        "occupancy": 4,
        "startTime": "00:00",
        "endTime": "00:59"
      },
      {
        "weekDay": "Mon",
        "occupancy": 4,
        "startTime": "01:00",
        "endTime": "01:59"
      },
      {
        "weekDay": "Mon",
        "occupancy": 4,
        "startTime": "02:00",
        "endTime": "02:59"
      },
      {
        "weekDay": "Mon",
        "occupancy": 4,
        "startTime": "03:00",
        "endTime": "03:59"
      },
      {
        "weekDay": "Mon",
        "occupancy": 4,
        "startTime": "04:00",
        "endTime": "04:59"
      },
      {
        "weekDay": "Mon",
        "occupancy": 4,
        "startTime": "05:00",
        "endTime": "05:59"
      },
      {
        "weekDay": "Mon",
        "occupancy": 4,
        "startTime": "06:00",
        "endTime": "06:59"
      },
      {
        "weekDay": "Mon",
        "occupancy": 4,
        "startTime": "07:00",
        "endTime": "07:59"
      },
      {
        "weekDay": "Mon",
        "occupancy": 4,
        "startTime": "08:00",
        "endTime": "08:59"
      },
      {
        "weekDay": "Mon",
        "occupancy": 4,
        "startTime": "09:00",
        "endTime": "09:59"
      },
      {
        "weekDay": "Mon",
        "occupancy": 4,
        "startTime": "10:00",
        "endTime": "10:59"
      },
      {
        "weekDay": "Mon",
        "occupancy": 4,
        "startTime": "11:00",
        "endTime": "11:59"
      },
      {
        "weekDay": "Mon",
        "occupancy": 4,
        "startTime": "12:00",
        "endTime": "12:59"
      },
      {
        "weekDay": "Mon",
        "occupancy": 4,
        "startTime": "13:00",
        "endTime": "13:59"
      },
      {
        "weekDay": "Mon",
        "occupancy": 4,
        "startTime": "14:00",
        "endTime": "14:59"
      },
      {
        "weekDay": "Mon",
        "occupancy": 4,
        "startTime": "15:00",
        "endTime": "15:59"
      },
      {
        "weekDay": "Mon",
        "occupancy": 4,
        "startTime": "16:00",
        "endTime": "16:59"
      },
      {
        "weekDay": "Mon",
        "occupancy": 4,
        "startTime": "17:00",
        "endTime": "17:59"
      },
      {
        "weekDay": "Mon",
        "occupancy": 4,
        "startTime": "18:00",
        "endTime": "18:59"
      },
      {
        "weekDay": "Mon",
        "occupancy": 3,
        "startTime": "19:00",
        "endTime": "19:59"
      },
      {
        "weekDay": "Mon",
        "occupancy": 3,
        "startTime": "20:00",
        "endTime": "20:59"
      },
      {
        "weekDay": "Mon",
        "occupancy": 3,
        "startTime": "21:00",
        "endTime": "21:59"
      },
      {
        "weekDay": "Mon",
        "occupancy": 3,
        "startTime": "22:00",
        "endTime": "22:59"
      },
      {
        "weekDay": "Mon",
        "occupancy": 3,
        "startTime": "23:00",
        "endTime": "23:59"
      },
      {
        "weekDay": "Sat",
        "occupancy": 5,
        "startTime": "00:00",
        "endTime": "00:59"
      },
      {
        "weekDay": "Sat",
        "occupancy": 5,
        "startTime": "01:00",
        "endTime": "01:59"
      },
      {
        "weekDay": "Sat",
        "occupancy": 5,
        "startTime": "02:00",
        "endTime": "02:59"
      },
      {
        "weekDay": "Sat",
        "occupancy": 5,
        "startTime": "03:00",
        "endTime": "03:59"
      },
      {
        "weekDay": "Sat",
        "occupancy": 5,
        "startTime": "04:00",
        "endTime": "04:59"
      },
      {
        "weekDay": "Sat",
        "occupancy": 5,
        "startTime": "05:00",
        "endTime": "05:59"
      },
      {
        "weekDay": "Sat",
        "occupancy": 5,
        "startTime": "06:00",
        "endTime": "06:59"
      },
      {
        "weekDay": "Sat",
        "occupancy": 5,
        "startTime": "07:00",
        "endTime": "07:59"
      },
      {
        "weekDay": "Sat",
        "occupancy": 5,
        "startTime": "08:00",
        "endTime": "08:59"
      },
      {
        "weekDay": "Sat",
        "occupancy": 5,
        "startTime": "09:00",
        "endTime": "09:59"
      },
      {
        "weekDay": "Sat",
        "occupancy": 5,
        "startTime": "10:00",
        "endTime": "10:59"
      },
      {
        "weekDay": "Sat",
        "occupancy": 5,
        "startTime": "11:00",
        "endTime": "11:59"
      },
      {
        "weekDay": "Sat",
        "occupancy": 5,
        "startTime": "12:00",
        "endTime": "12:59"
      },
      {
        "weekDay": "Sat",
        "occupancy": 5,
        "startTime": "13:00",
        "endTime": "13:59"
      },
      {
        "weekDay": "Sat",
        "occupancy": 5,
        "startTime": "14:00",
        "endTime": "14:59"
      },
      {
        "weekDay": "Sat",
        "occupancy": 5,
        "startTime": "15:00",
        "endTime": "15:59"
      },
      {
        "weekDay": "Sat",
        "occupancy": 5,
        "startTime": "16:00",
        "endTime": "16:59"
      },
      {
        "weekDay": "Sat",
        "occupancy": 5,
        "startTime": "17:00",
        "endTime": "17:59"
      },
      {
        "weekDay": "Sat",
        "occupancy": 5,
        "startTime": "18:00",
        "endTime": "18:59"
      },
      {
        "weekDay": "Sat",
        "occupancy": 5,
        "startTime": "19:00",
        "endTime": "19:59"
      },
      {
        "weekDay": "Sat",
        "occupancy": 5,
        "startTime": "20:00",
        "endTime": "20:59"
      },
      {
        "weekDay": "Sat",
        "occupancy": 4,
        "startTime": "21:00",
        "endTime": "21:59"
      },
      {
        "weekDay": "Sat",
        "occupancy": 4,
        "startTime": "22:00",
        "endTime": "22:59"
      },
      {
        "weekDay": "Sat",
        "occupancy": 4,
        "startTime": "23:00",
        "endTime": "23:59"
      },
      {
        "weekDay": "Sun",
        "occupancy": 4,
        "startTime": "00:00",
        "endTime": "00:59"
      },
      {
        "weekDay": "Sun",
        "occupancy": 5,
        "startTime": "01:00",
        "endTime": "01:59"
      },
      {
        "weekDay": "Sun",
        "occupancy": 5,
        "startTime": "02:00",
        "endTime": "02:59"
      },
      {
        "weekDay": "Sun",
        "occupancy": 5,
        "startTime": "03:00",
        "endTime": "03:59"
      },
      {
        "weekDay": "Sun",
        "occupancy": 4,
        "startTime": "04:00",
        "endTime": "04:59"
      },
      {
        "weekDay": "Sun",
        "occupancy": 4,
        "startTime": "05:00",
        "endTime": "05:59"
      },
      {
        "weekDay": "Sun",
        "occupancy": 4,
        "startTime": "06:00",
        "endTime": "06:59"
      },
      {
        "weekDay": "Sun",
        "occupancy": 4,
        "startTime": "07:00",
        "endTime": "07:59"
      },
      {
        "weekDay": "Sun",
        "occupancy": 4,
        "startTime": "08:00",
        "endTime": "08:59"
      },
      {
        "weekDay": "Sun",
        "occupancy": 4,
        "startTime": "09:00",
        "endTime": "09:59"
      },
      {
        "weekDay": "Sun",
        "occupancy": 4,
        "startTime": "10:00",
        "endTime": "10:59"
      },
      {
        "weekDay": "Sun",
        "occupancy": 4,
        "startTime": "11:00",
        "endTime": "11:59"
      },
      {
        "weekDay": "Sun",
        "occupancy": 4,
        "startTime": "12:00",
        "endTime": "12:59"
      },
      {
        "weekDay": "Sun",
        "occupancy": 4,
        "startTime": "13:00",
        "endTime": "13:59"
      },
      {
        "weekDay": "Sun",
        "occupancy": 4,
        "startTime": "14:00",
        "endTime": "14:59"
      },
      {
        "weekDay": "Sun",
        "occupancy": 4,
        "startTime": "15:00",
        "endTime": "15:59"
      },
      {
        "weekDay": "Sun",
        "occupancy": 4,
        "startTime": "16:00",
        "endTime": "16:59"
      },
      {
        "weekDay": "Sun",
        "occupancy": 4,
        "startTime": "17:00",
        "endTime": "17:59"
      },
      {
        "weekDay": "Sun",
        "occupancy": 4,
        "startTime": "18:00",
        "endTime": "18:59"
      },
      {
        "weekDay": "Sun",
        "occupancy": 4,
        "startTime": "19:00",
        "endTime": "19:59"
      },
      {
        "weekDay": "Sun",
        "occupancy": 4,
        "startTime": "20:00",
        "endTime": "20:59"
      },
      {
        "weekDay": "Sun",
        "occupancy": 4,
        "startTime": "21:00",
        "endTime": "21:59"
      },
      {
        "weekDay": "Sun",
        "occupancy": 4,
        "startTime": "22:00",
        "endTime": "22:59"
      },
      {
        "weekDay": "Sun",
        "occupancy": 4,
        "startTime": "23:00",
        "endTime": "23:59"
      },
      {
        "weekDay": "Thu",
        "occupancy": 4,
        "startTime": "00:00",
        "endTime": "00:59"
      },
      {
        "weekDay": "Thu",
        "occupancy": 4,
        "startTime": "01:00",
        "endTime": "01:59"
      },
      {
        "weekDay": "Thu",
        "occupancy": 4,
        "startTime": "02:00",
        "endTime": "02:59"
      },
      {
        "weekDay": "Thu",
        "occupancy": 4,
        "startTime": "03:00",
        "endTime": "03:59"
      },
      {
        "weekDay": "Thu",
        "occupancy": 3,
        "startTime": "04:00",
        "endTime": "04:59"
      },
      {
        "weekDay": "Thu",
        "occupancy": 3,
        "startTime": "05:00",
        "endTime": "05:59"
      },
      {
        "weekDay": "Thu",
        "occupancy": 3,
        "startTime": "06:00",
        "endTime": "06:59"
      },
      {
        "weekDay": "Thu",
        "occupancy": 3,
        "startTime": "07:00",
        "endTime": "07:59"
      },
      {
        "weekDay": "Thu",
        "occupancy": 3,
        "startTime": "08:00",
        "endTime": "08:59"
      },
      {
        "weekDay": "Thu",
        "occupancy": 3,
        "startTime": "09:00",
        "endTime": "09:59"
      },
      {
        "weekDay": "Thu",
        "occupancy": 4,
        "startTime": "10:00",
        "endTime": "10:59"
      },
      {
        "weekDay": "Thu",
        "occupancy": 4,
        "startTime": "11:00",
        "endTime": "11:59"
      },
      {
        "weekDay": "Thu",
        "occupancy": 4,
        "startTime": "12:00",
        "endTime": "12:59"
      },
      {
        "weekDay": "Thu",
        "occupancy": 4,
        "startTime": "13:00",
        "endTime": "13:59"
      },
      {
        "weekDay": "Thu",
        "occupancy": 4,
        "startTime": "14:00",
        "endTime": "14:59"
      },
      {
        "weekDay": "Thu",
        "occupancy": 4,
        "startTime": "15:00",
        "endTime": "15:59"
      },
      {
        "weekDay": "Thu",
        "occupancy": 4,
        "startTime": "16:00",
        "endTime": "16:59"
      },
      {
        "weekDay": "Thu",
        "occupancy": 4,
        "startTime": "17:00",
        "endTime": "17:59"
      },
      {
        "weekDay": "Thu",
        "occupancy": 5,
        "startTime": "18:00",
        "endTime": "18:59"
      },
      {
        "weekDay": "Thu",
        "occupancy": 5,
        "startTime": "19:00",
        "endTime": "19:59"
      },
      {
        "weekDay": "Thu",
        "occupancy": 5,
        "startTime": "20:00",
        "endTime": "20:59"
      },
      {
        "weekDay": "Thu",
        "occupancy": 5,
        "startTime": "21:00",
        "endTime": "21:59"
      },
      {
        "weekDay": "Thu",
        "occupancy": 5,
        "startTime": "22:00",
        "endTime": "22:59"
      },
      {
        "weekDay": "Thu",
        "occupancy": 5,
        "startTime": "23:00",
        "endTime": "23:59"
      },
      {
        "weekDay": "Tue",
        "occupancy": 3,
        "startTime": "00:00",
        "endTime": "00:59"
      },
      {
        "weekDay": "Tue",
        "occupancy": 3,
        "startTime": "01:00",
        "endTime": "01:59"
      },
      {
        "weekDay": "Tue",
        "occupancy": 3,
        "startTime": "02:00",
        "endTime": "02:59"
      },
      {
        "weekDay": "Tue",
        "occupancy": 3,
        "startTime": "03:00",
        "endTime": "03:59"
      },
      {
        "weekDay": "Tue",
        "occupancy": 3,
        "startTime": "04:00",
        "endTime": "04:59"
      },
      {
        "weekDay": "Tue",
        "occupancy": 3,
        "startTime": "05:00",
        "endTime": "05:59"
      },
      {
        "weekDay": "Tue",
        "occupancy": 3,
        "startTime": "06:00",
        "endTime": "06:59"
      },
      {
        "weekDay": "Tue",
        "occupancy": 3,
        "startTime": "07:00",
        "endTime": "07:59"
      },
      {
        "weekDay": "Tue",
        "occupancy": 3,
        "startTime": "08:00",
        "endTime": "08:59"
      },
      {
        "weekDay": "Tue",
        "occupancy": 3,
        "startTime": "09:00",
        "endTime": "09:59"
      },
      {
        "weekDay": "Tue",
        "occupancy": 4,
        "startTime": "10:00",
        "endTime": "10:59"
      },
      {
        "weekDay": "Tue",
        "occupancy": 4,
        "startTime": "11:00",
        "endTime": "11:59"
      },
      {
        "weekDay": "Tue",
        "occupancy": 4,
        "startTime": "12:00",
        "endTime": "12:59"
      },
      {
        "weekDay": "Tue",
        "occupancy": 4,
        "startTime": "13:00",
        "endTime": "13:59"
      },
      {
        "weekDay": "Tue",
        "occupancy": 4,
        "startTime": "14:00",
        "endTime": "14:59"
      },
      {
        "weekDay": "Tue",
        "occupancy": 4,
        "startTime": "15:00",
        "endTime": "15:59"
      },
      {
        "weekDay": "Tue",
        "occupancy": 4,
        "startTime": "16:00",
        "endTime": "16:59"
      },
      {
        "weekDay": "Tue",
        "occupancy": 4,
        "startTime": "17:00",
        "endTime": "17:59"
      },
      {
        "weekDay": "Tue",
        "occupancy": 4,
        "startTime": "18:00",
        "endTime": "18:59"
      },
      {
        "weekDay": "Tue",
        "occupancy": 4,
        "startTime": "19:00",
        "endTime": "19:59"
      },
      {
        "weekDay": "Tue",
        "occupancy": 4,
        "startTime": "20:00",
        "endTime": "20:59"
      },
      {
        "weekDay": "Tue",
        "occupancy": 4,
        "startTime": "21:00",
        "endTime": "21:59"
      },
      {
        "weekDay": "Tue",
        "occupancy": 4,
        "startTime": "22:00",
        "endTime": "22:59"
      },
      {
        "weekDay": "Tue",
        "occupancy": 4,
        "startTime": "23:00",
        "endTime": "23:59"
      },
      {
        "weekDay": "Wed",
        "occupancy": 4,
        "startTime": "00:00",
        "endTime": "00:59"
      },
      {
        "weekDay": "Wed",
        "occupancy": 4,
        "startTime": "01:00",
        "endTime": "01:59"
      },
      {
        "weekDay": "Wed",
        "occupancy": 4,
        "startTime": "02:00",
        "endTime": "02:59"
      },
      {
        "weekDay": "Wed",
        "occupancy": 4,
        "startTime": "03:00",
        "endTime": "03:59"
      },
      {
        "weekDay": "Wed",
        "occupancy": 4,
        "startTime": "04:00",
        "endTime": "04:59"
      },
      {
        "weekDay": "Wed",
        "occupancy": 4,
        "startTime": "05:00",
        "endTime": "05:59"
      },
      {
        "weekDay": "Wed",
        "occupancy": 4,
        "startTime": "06:00",
        "endTime": "06:59"
      },
      {
        "weekDay": "Wed",
        "occupancy": 4,
        "startTime": "07:00",
        "endTime": "07:59"
      },
      {
        "weekDay": "Wed",
        "occupancy": 4,
        "startTime": "08:00",
        "endTime": "08:59"
      },
      {
        "weekDay": "Wed",
        "occupancy": 4,
        "startTime": "09:00",
        "endTime": "09:59"
      },
      {
        "weekDay": "Wed",
        "occupancy": 4,
        "startTime": "10:00",
        "endTime": "10:59"
      },
      {
        "weekDay": "Wed",
        "occupancy": 4,
        "startTime": "11:00",
        "endTime": "11:59"
      },
      {
        "weekDay": "Wed",
        "occupancy": 4,
        "startTime": "12:00",
        "endTime": "12:59"
      },
      {
        "weekDay": "Wed",
        "occupancy": 4,
        "startTime": "13:00",
        "endTime": "13:59"
      },
      {
        "weekDay": "Wed",
        "occupancy": 4,
        "startTime": "14:00",
        "endTime": "14:59"
      },
      {
        "weekDay": "Wed",
        "occupancy": 4,
        "startTime": "15:00",
        "endTime": "15:59"
      },
      {
        "weekDay": "Wed",
        "occupancy": 4,
        "startTime": "16:00",
        "endTime": "16:59"
      },
      {
        "weekDay": "Wed",
        "occupancy": 4,
        "startTime": "17:00",
        "endTime": "17:59"
      },
      {
        "weekDay": "Wed",
        "occupancy": 4,
        "startTime": "18:00",
        "endTime": "18:59"
      },
      {
        "weekDay": "Wed",
        "occupancy": 4,
        "startTime": "19:00",
        "endTime": "19:59"
      },
      {
        "weekDay": "Wed",
        "occupancy": 4,
        "startTime": "20:00",
        "endTime": "20:59"
      },
      {
        "weekDay": "Wed",
        "occupancy": 4,
        "startTime": "21:00",
        "endTime": "21:59"
      },
      {
        "weekDay": "Wed",
        "occupancy": 4,
        "startTime": "22:00",
        "endTime": "22:59"
      },
      {
        "weekDay": "Wed",
        "occupancy": 4,
        "startTime": "23:00",
        "endTime": "23:59"
      }
    ],
    "suboperatorName": "ENGIE Vianeo",
    "countryCode": "NL",
    "partyId": "GFX",
    "roamingSource": "ocpi",
    "heavyVehicles": {
      "dedicated": false,
      "restrictions": [],
      "amenities": []
    }
  }
]
```

**Comment by cyberjunky** [comment]
Can you try new version 0.1.14? I have fixed an issue where updating stopped if any of the chargers returned no data.

**Comment by cyberjunky** [comment]
If status in fetched data is the same as what HA tells you. What can I do?
What are the id's i see you blanked several why is that? They are public... I have 6 in my HA they are correct.

**Comment by jefdriesen** [comment]
I also tested the new version, but it doesn't fix the problem. I applied an extra debug [patch](https://github.com/user-attachments/files/23828822/debug.patch) to log the server response. This confirms the integration contacts the server and the returned response contains the correct status. But the HA status isn't updated.

[home-assistant_shell_recharge.log](https://github.com/user-attachments/files/23828835/home-assistant_shell_recharge.log)

Both chargers have status='Occupied' returned by the server:

`2025-11-28 19:28:38.537 DEBUG (MainThread) [custom_components.shell_recharge.coordinator] uid=5040351 externalId='AAAAAA' evses=[Evse(uid=5759356, externalId='BEALLEGOAAAAAA1', evseId='BE*ALL*EGOAAAAAA1', status='Occupied', updated='2025-11-28T16:22:59Z'), Evse(uid=5759357, externalId='BEALLEGOAAAAAA2', evseId='BE*ALL*EGOAAAAAA2', status='Occupied', authorizationMethods=['NewMotionApp', 'RFIDToken'], physicalReference='BE*ALL*EGOAAAAAA2', updated='2025-11-28T18:11:48Z')]`

The fist HA sensor stays at status='Available' (wrong) and the second at status='Occupied' :

`2025-11-28 19:28:38.544 DEBUG (MainThread) [custom_components.shell_recharge.sensor] uid=5759357 externalId='BEALLEGOAAAAAA2' evseId='BE*ALL*EGOAAAAAA2' status='Available' connectors=[Connector(uid=5871366, externalId='2', connectorType='Type2', electricalProperties=ElectricalProperties(powerType='AC3Phase', voltage=230, amperage=16.0, maxElectricPower=11.0), fixedCable=False, tariff=Tariff(startFee=0.0, perMinute=0.0, perKWh=0.63, currency='EUR', updated='2025-11-28T17:53:28Z', updatedBy='Default', structure='Flat'), updated='2025-08-07T20:59:40Z', updatedBy='Feed', externalTariffId='3472')] authorizationMethods=['NewMotionApp', 'RFIDToken'] physicalReference='BE*ALL*EGOAAAAAA2' updated='2025-11-28T16:52:12Z'`

`2025-11-28 19:28:38.545 DEBUG (MainThread) [custom_components.shell_recharge.sensor] uid=5759356 externalId='BEALLEGOAAAAAA1' evseId='BE*ALL*EGOAAAAAA1' status='Occupied' connectors=[Connector(uid=5871365, externalId='1', connectorType='Type2', electricalProperties=ElectricalProperties(powerType='AC3Phase', voltage=230, amperage=16.0, maxElectricPower=11.0), fixedCable=False, tariff=Tariff(startFee=0.0, perMinute=0.0, perKWh=0.63, currency='EUR', updated='2025-11-28T17:53:28Z', updatedBy='Default', structure='Flat'), updated='2025-08-07T20:59:40Z', updatedBy='Feed', externalTariffId='3472')] authorizationMethods=['NewMotionApp', 'RFIDToken'] physicalReference='BE*ALL*EGOAAAAAA1' updated='2025-11-28T16:22:59Z'`

**Comment by gschot** [comment]
I just updated to 0.1.14 to check. I'll report back the findings.

**Comment by cyberjunky** [comment]
Version 0.1.15, fingers crossed, hoping this is finally fixed.

**Comment by svendaems** [comment]
Also positive feedback from me, both charges added to my HA updated properly in the last hour

**Comment by gschot** [comment]
Yes, I have also received updates, 0.1.16 seems to be working. I'll monitor it some more. Thanks for the effort!
